# Generated by Django 3.0.4 on 2020-04-17 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200417_1653'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='languages',
            new_name='language',
        ),
    ]
