# Generated by Django 3.0.4 on 2020-05-24 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0005_auto_20200522_1321'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=5000)),
                ('correct_answer', models.SmallIntegerField()),
                ('mark', models.SmallIntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='test',
            old_name='correct_answer',
            new_name='max_mark',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='mark',
            new_name='quantity_questions',
        ),
        migrations.RemoveField(
            model_name='test',
            name='text',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.AddField(
            model_name='question',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.Test'),
        ),
    ]
